01-fizz_buzz/config/routes.rb
Fizzbuzz::Application.routes.draw do
  resources :games, except: [:edit, :destroy] do
    resources :frames, except: [:show, :new]
  end

  devise_for :users, path: :users

 root :to => 'games#index'
end

01-fizz_buzz/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :manage, Game, :user_id => user.id
      can :manage, Frame, game: { :user_id => user.id }
    end
  end
end

01-fizz_buzz/app/models/concerns/fizz_buzzable.rb
module FizzBuzzable
  extend ActiveSupport::Concern

  def fizz_buzzify(number)
    result = ''

    result += 'Fizz' if fizz?(number)
    result += 'Buzz' if buzz?(number)
    result = number if result.empty?
    result
  end

  def fizz?(number)
    number % 3 == 0
  end

  def buzz?(number)
    number % 5 == 0
  end
end

01-fizz_buzz/app/models/frame.rb
# == Schema Information
#
# Table name: frames
#
#  id         :integer          not null, primary key
#  game_id    :integer
#  position   :integer
#  fizz_buzz  :string(255)
#  answer     :integer
#  correct    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Frame < ActiveRecord::Base
  include FizzBuzzable

  attr_accessible :answer

  belongs_to :game

  acts_as_list :scope => :game

  before_create :set_fizz_buzz
  before_update :mark

  def options
    unique_random(5, position, [fizz_buzzify(position)]).inject([]) do |acc, option|
      acc << [option, false]
    end.shuffle
  end

  def set_fizz_buzz
    self.fizz_buzz ||= fizz_buzzify(position)
  end

  private

  def mark
    self.correct = fizz_buzz == answer
  end

  def unique_random(count, median, excluded_values = [])
    while excluded_values.size <= count
      random_fizz = fizz_buzzify([Random.rand(median-10..median+10), 1].max)

      unless excluded_values.include?(random_fizz)
        excluded_values << random_fizz
      end

      unique_random(count, median, excluded_values)
    end

    excluded_values
  end
end

01-fizz_buzz/app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  score          :integer
#  time_to_finish :integer
#  high_number    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Game < ActiveRecord::Base
  attr_accessible :high_number, :time_to_finish

  belongs_to :user
  has_many :frames, order: :position

  after_create :create_first_frame

  def first_frame
    frames.first
  end

  private

  def create_first_frame
    frames.create
  end
end

01-fizz_buzz/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string(255)
#  last_name              :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  admin                  :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me

  has_many :games
end

01-fizz_buzz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

01-fizz_buzz/app/controllers/frames_controller.rb
class FramesController < ApplicationController
  load_and_authorize_resource :game
  load_and_authorize_resource :frame, through: :game

  respond_to :html, :json

  def index
  end

  def create
    @frame.save
    respond_with @frame, location: nil
  end

  def edit
    @next_frame_id = @frame.lower_item.id if @frame.lower_item
  end

  def update
    @frame.update_attributes(params[:frame])

    respond_with @frame do |format|
      format.json { render json: @frame.to_json }
    end
  end
end

01-fizz_buzz/app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource through: :current_user

  respond_to :html, :json

  def index
  end

  def show
  end

  def new
  end

  def create
    @game.save

    respond_with @game, location: edit_game_frame_path(@game, @game.first_frame)
  end

  def update
  end

  def destroy
  end
end

01-fizz_buzz/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

01-fizz_buzz/app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash
    return nil if flash[:error].blank? && flash[:warning].blank? && flash[:notice].blank? && flash[:alert].blank?

    if flash[:notice].present?
      buffer = '<div data-alert="" class="alert-box radius success">'
      buffer << flash[:notice]
    elsif flash[:alert].present?
      buffer = '<div data-alert="" class="alert-box radius alert">'
      buffer << flash[:alert]
    elsif flash[:warning].present?
      buffer = '<div data-alert="" class="alert-box radius alert">'
      buffer << flash[:warning]
    elsif flash[:error].present?
      buffer = '<div data-alert="" class="alert-box radius alert">'
      buffer << "<strong>Uh oh!</strong> #{flash[:error]}"
    end

    buffer << '<a href="" class="close">&times;</a></div>'
    buffer.html_safe
  end
end

01-fizz_buzz/app/helpers/frames_helper.rb
module FramesHelper
end

01-fizz_buzz/app/views/frames/edit.html.erb
<div class="row">
  <div class="columns small-6 small-centered">
    <div class="panel sequence">
      <%= form_for @frame, url: game_frame_path(@game, @frame, format: :json), remote: true,
            html: { :"data-game-id" => @game.id, :"data-position" => @frame.position, :"data-next-frame-id" => "#{@next_frame_id}" } do |f| %>
        <div class="fields">
          <%  @frame.options.each do |option| %>
            <%= f.label "answer_#{option[0].to_s.downcase}" do %>
              <%= f.radio_button :answer, option[0] %>
              <%= option[0] %>
            <% end %>
          <% end %>
        </div>

        <div class="actions">
          <%= f.submit "Answer", class: 'button' %>
        </div>
      <% end %>
    </div>

    <div id="end-game">
      <%= link_to "Forfeit", game_path(@game), class: 'button small alert' %>
    </div>
  </div>
</div>

01-fizz_buzz/app/views/frames/new.html.erb
<%= form_for @frame, url: game_frames_path(@game, format: :json), remote: true do |f| %>
  <%= render 'form', f: f %>
<% end %>

01-fizz_buzz/app/views/games/index.html.erb
<div class="row">
  <div class="columns small-8 small-centered">
    <section id="games-index">
      <% if @games.present? %>
        <table>
          <thead>
            <tr>
              <th>Game #</th>
              <th># Correct Answers</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @games.each do |game| %>
              <tr>
                <td><%= game.id %></td>
                <td><%= game.frames.count %></td>
                <td><%= game.created_at.strftime("%B %d, %Y") %></td>
                <td><%= link_to "See Results", game_path(game), class: 'button small' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="no-games">
          <h1>You don't have any games yet.</h1>
          <%= link_to "Play now", new_game_path, class: 'button large' %>
        </div>
      <% end %>
    </section>
  </div>
</div>

01-fizz_buzz/app/views/games/new.html.erb
<div class="row">
  <div class="columns small-12">
    <section id="new-game">
      <h1>I'm ready when you are.</h1>
      <%= button_to "Start Game", games_path, class: 'button large' %>
    </section>
  </div>
</div>

01-fizz_buzz/app/views/games/show.html.erb
<div class="row">
  <section class="columns small-6 small-centered">
    <h1>Game #<%= @game.id %></h1>
    <table id="game-results">
      <thead>
        <tr>
          <th class="correct-answer">Correct Answer</th>
          <th class="your-answer">Your Answer</th>
        </tr>
      </thead>
      <tbody>
        <% 100.times do |index| %>
          <% if @game.frames[index].present? %>
            <tr>
              <td class="correct-answer"><%= @game.frames[index].fizz_buzz %> (<%= index + 1 %>)</td>
              <td class="your-answer"><%= @game.frames[index].answer %></td>
            </tr>
          <% else %>
            <tr>
              <td class="correct-answer"><%= Frame.new(position: index + 1).set_fizz_buzz %> (<%= index + 1 %>)</td>
              <td class="your-answer"></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

01-fizz_buzz/app/views/home/show.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>

01-fizz_buzz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "The FizzBuzz Challenge" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller.controller_name %>">
    <nav class="top-bar">
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1><a href="/">The FizzBuzz Challenge</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if user_signed_in? %>
            <li class="divider"></li>
            <li><%= link_to "Your Games", games_path %></li>
            <li class="divider"></li>
            <li><%= link_to "New Game", new_game_path %></li>
          <% end %>
          <li class="divider"></li>
          <li class="has-form">
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: :button %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: :button %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li class="has-form">
            <% unless user_signed_in? %>
              <%= link_to "Sign up", new_registration_path('user'), class: 'button' %>
            <% end %>
          </li>
        </ul>
      </section>
    </nav>

    <div class="row">
      <div id="alert-wrapper" class="columns small-9 small-centered">
        <%= display_flash %>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>